import { jsPDF } from "jspdf";
import { CVProfile } from "../types";

export const generatePDF = (cv: CVProfile) => {
  const doc = new jsPDF();
  let cursorY = 20;

  // Colors
  const darkColor = "#2A0A10"; // Dark Bordeaux
  const goldColor = "#D4AF37"; // Gold

  // Helper to check page break
  const checkPageBreak = (height: number = 10) => {
    if (cursorY + height > 280) {
      doc.addPage();
      cursorY = 20;
    }
  };

  // Header Background
  doc.setFillColor(245, 245, 245);
  doc.rect(0, 0, 210, 50, 'F');

  // Name
  doc.setTextColor(darkColor);
  doc.setFont("times", "bold");
  doc.setFontSize(22);
  doc.text(cv.fullName.toUpperCase(), 20, 25);

  // Title
  doc.setTextColor(goldColor);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.text(cv.title.toUpperCase(), 20, 32);

  // Contact Info (Right aligned)
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(cv.email, 190, 20, { align: 'right' });
  doc.text(cv.phone, 190, 25, { align: 'right' });
  doc.text(cv.location, 190, 30, { align: 'right' });

  cursorY = 60;

  // Section Header Helper
  const addSection = (title: string) => {
    checkPageBreak(15);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(darkColor);
    doc.text(title.toUpperCase(), 20, cursorY);
    doc.setDrawColor(212, 175, 55); // Gold line
    doc.setLineWidth(0.5);
    doc.line(20, cursorY + 2, 190, cursorY + 2);
    cursorY += 10;
  };

  // Summary
  addSection("Professional Summary");
  doc.setFont("times", "normal");
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  const splitSummary = doc.splitTextToSize(cv.summary, 170);
  checkPageBreak(splitSummary.length * 5);
  doc.text(splitSummary, 20, cursorY);
  cursorY += splitSummary.length * 5 + 5;

  // Experience
  addSection("Experience");
  cv.experience.forEach((exp) => {
    checkPageBreak(25);
    // Role & Company
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`${exp.role}`, 20, cursorY);
    
    doc.setFont("helvetica", "normal");
    doc.text(`${exp.company} | ${exp.duration}`, 190, cursorY, { align: "right" });
    cursorY += 6;

    // Description
    doc.setFont("times", "normal");
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const splitDesc = doc.splitTextToSize(exp.description, 170);
    checkPageBreak(splitDesc.length * 5);
    doc.text(splitDesc, 20, cursorY);
    cursorY += splitDesc.length * 5 + 6;
  });

  // Education
  addSection("Education");
  cv.education.forEach((edu) => {
    checkPageBreak(15);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(edu.institution, 20, cursorY);
    
    doc.setFont("helvetica", "normal");
    doc.text(edu.year, 190, cursorY, { align: "right" });
    cursorY += 5;

    doc.setFont("times", "normal");
    doc.setFontSize(10);
    doc.text(edu.degree, 20, cursorY);
    cursorY += 8;
  });

  // Skills
  addSection("Skills");
  doc.setFont("times", "normal");
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const skillsText = cv.skills.join(" • ");
  const splitSkills = doc.splitTextToSize(skillsText, 170);
  checkPageBreak(splitSkills.length * 5);
  doc.text(splitSkills, 20, cursorY);
  cursorY += splitSkills.length * 5 + 5;

  // Hobbies
  if (cv.hobbies && cv.hobbies.length > 0) {
    addSection("Interests");
    doc.setFont("times", "normal");
    doc.setFontSize(10);
    const hobbiesText = cv.hobbies.join(", ");
    const splitHobbies = doc.splitTextToSize(hobbiesText, 170);
    checkPageBreak(splitHobbies.length * 5);
    doc.text(splitHobbies, 20, cursorY);
  }

  // Footer Branding
  const pageCount = doc.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Metis - Trigenys Group", 105, 290, { align: "center" });
  }

  doc.save(`${cv.fullName.replace(/\s+/g, '_')}_CV.pdf`);
};